/**
 * Integration tests for SchedulePdfService
 *
 * Tests target the two pure builder methods:
 *   buildDutyPdf(data)       — duty schedule grouped by department + date
 *   buildWeeklyWorkPdf(data) — weekly work items in table format
 *
 * No database. No mocks. The builders accept plain JS objects and return
 * a real PDF Buffer generated by PDFKit. Tests verify:
 *   • Correct Buffer type
 *   • Valid PDF magic bytes (%PDF)
 *   • Non-trivial file size (has content)
 *   • Key domain strings are embedded in the PDF bytes
 *   • Edge cases: empty shifts, empty items, missing optional fields
 *   • Type-guard errors for wrong schedule_type input
 */

const SchedulePdfService = require('../../src/services/SchedulePdfService');
const { ScheduleType, ScheduleStatus } = require('../../src/utils/enums');

// ─── Fixture helpers ──────────────────────────────────────────────────────────

function makeDutyData(overrides = {}) {
  return {
    schedule_id:             100,
    schedule_type:           ScheduleType.DUTY,
    week:                    10,
    year:                    2024,
    status:                  ScheduleStatus.APPROVED,
    source_department_name:  'Khoa Noi',
    owner_department_name:   'Phong KHTH',
    departments: [
      {
        department_id:   3,
        department_name: 'Khoa Noi',
        department_code: 'KHOA-NOI',
        dates: [
          {
            date: '2024-03-04',
            shifts: [
              {
                shift_id:   200,
                shift_type: 'morning',
                start_time: '07:00:00',
                end_time:   '12:00:00',
                max_staff:  5,
                assignments: [
                  { full_name: 'Nguyen Van A', employee_code: 'NV001' },
                  { full_name: 'Tran Thi B',   employee_code: 'NV002' },
                ],
              },
              {
                shift_id:   201,
                shift_type: 'night',
                start_time: '18:00:00',
                end_time:   '23:00:00',
                max_staff:  3,
                assignments: [],      // no staff yet → should show placeholder
              },
            ],
          },
          {
            date: '2024-03-05',
            shifts: [
              {
                shift_id:   202,
                shift_type: 'afternoon',
                start_time: '13:00:00',
                end_time:   '17:00:00',
                max_staff:  4,
                assignments: [
                  { full_name: 'Le Van C', employee_code: 'NV003' },
                ],
              },
            ],
          },
        ],
      },
      {
        department_id:   4,
        department_name: 'Khoa Ngoai',
        department_code: 'KHOA-NGOAI',
        dates: [
          {
            date: '2024-03-04',
            shifts: [
              {
                shift_id:   203,
                shift_type: 'morning',
                start_time: '07:00:00',
                end_time:   '12:00:00',
                max_staff:  6,
                assignments: [
                  { full_name: 'Pham Thi D', employee_code: 'NV004' },
                ],
              },
            ],
          },
        ],
      },
    ],
    ...overrides,
  };
}

function makeWeeklyData(overrides = {}) {
  return {
    schedule_id:            200,
    schedule_type:          ScheduleType.WEEKLY_WORK,
    week:                   5,
    year:                   2025,
    status:                 ScheduleStatus.APPROVED,
    owner_department_name:  'Phong KHTH',
    items: [
      {
        weekly_work_item_id: 1,
        work_date:    '2025-02-03',
        content:      'Hospital quality review meeting',
        location:     'Conference Room A',
        participants: 'Dr. Anh, Nurse Thu, Admin Hoa',
      },
      {
        weekly_work_item_id: 2,
        work_date:    '2025-02-04',
        content:      'Budget planning session',
        location:     'Finance Office',
        participants: 'Director Nam, CFO Lan',
      },
      {
        weekly_work_item_id: 3,
        work_date:    '2025-02-05',
        content:      'Staff training on new EHR system',
        location:     null,          // no location → should render '—'
        participants: null,          // no participants → should render '—'
      },
    ],
    ...overrides,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// buildDutyPdf
// ─────────────────────────────────────────────────────────────────────────────

describe('SchedulePdfService.buildDutyPdf', () => {
  let pdfBuffer;

  beforeAll(async () => {
    pdfBuffer = await SchedulePdfService.buildDutyPdf(makeDutyData());
  });

  // ── Output type & validity ──────────────────────────────────────────────

  it('returns a Buffer', () => {
    expect(Buffer.isBuffer(pdfBuffer)).toBe(true);
  });

  it('starts with the PDF magic bytes %PDF', () => {
    expect(pdfBuffer.slice(0, 4).toString()).toBe('%PDF');
  });

  it('produces a non-trivial file (> 6 KB)', () => {
    expect(pdfBuffer.length).toBeGreaterThan(6 * 1024);
  });

  // ── Schedule metadata embedded in PDF ──────────────────────────────────

  it('embeds the week number', () => {
    expect(pdfBuffer.toString('latin1')).toContain('10');
  });

  it('embeds the year', () => {
    expect(pdfBuffer.toString('latin1')).toContain('2024');
  });

  // ── Department section content ──────────────────────────────────────────

  it('embeds both department codes', () => {
    const raw = pdfBuffer.toString('latin1');
    expect(raw).toContain('KHOA-NOI');
    expect(raw).toContain('KHOA-NGOAI');
  });

  // ── Shift assignment content ────────────────────────────────────────────

  it('embeds employee codes for assigned staff', () => {
    const raw = pdfBuffer.toString('latin1');
    expect(raw).toContain('NV001');
    expect(raw).toContain('NV002');
    expect(raw).toContain('NV003');
    expect(raw).toContain('NV004');
  });

  it('embeds shift time values', () => {
    const raw = pdfBuffer.toString('latin1');
    expect(raw).toContain('07:00');
    expect(raw).toContain('12:00');
    expect(raw).toContain('13:00');
    expect(raw).toContain('17:00');
  });

  it('embeds max_staff numbers', () => {
    const raw = pdfBuffer.toString('latin1');
    expect(raw).toContain('5');   // max_staff of shift 200
    expect(raw).toContain('3');   // max_staff of shift 201
  });

  it('embeds formatted dates', () => {
    const raw = pdfBuffer.toString('latin1');
    expect(raw).toContain('04/03/2024');
    expect(raw).toContain('05/03/2024');
  });

  // ── Edge: no departments ────────────────────────────────────────────────

  it('produces a valid PDF when departments list is empty', async () => {
    const buf = await SchedulePdfService.buildDutyPdf(makeDutyData({ departments: [] }));
    expect(Buffer.isBuffer(buf)).toBe(true);
    expect(buf.slice(0, 4).toString()).toBe('%PDF');
  });

  // ── Edge: shift with no assignments ────────────────────────────────────

  it('handles a shift with no assignments without throwing', async () => {
    const data = makeDutyData();
    // Remove all assignments from every shift
    data.departments.forEach(d =>
      d.dates.forEach(day =>
        day.shifts.forEach(s => { s.assignments = []; })
      )
    );
    const buf = await SchedulePdfService.buildDutyPdf(data);
    expect(Buffer.isBuffer(buf)).toBe(true);
    expect(buf.slice(0, 4).toString()).toBe('%PDF');
  });

  // ── Edge: optional fields missing ──────────────────────────────────────

  it('handles missing source_department_name gracefully', async () => {
    const buf = await SchedulePdfService.buildDutyPdf(
      makeDutyData({ source_department_name: undefined, owner_department_name: undefined })
    );
    expect(Buffer.isBuffer(buf)).toBe(true);
  });

  // ── Type-guard ──────────────────────────────────────────────────────────

  it('throws when called with a weekly_work schedule object', async () => {
    await expect(
      SchedulePdfService.buildDutyPdf({ ...makeDutyData(), schedule_type: 'weekly_work' })
    ).rejects.toThrow('buildDutyPdf requires a duty schedule data object');
  });

  it('throws when called with null', async () => {
    await expect(SchedulePdfService.buildDutyPdf(null))
      .rejects.toThrow('buildDutyPdf requires a duty schedule data object');
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// buildWeeklyWorkPdf
// ─────────────────────────────────────────────────────────────────────────────

describe('SchedulePdfService.buildWeeklyWorkPdf', () => {
  let pdfBuffer;

  beforeAll(async () => {
    pdfBuffer = await SchedulePdfService.buildWeeklyWorkPdf(makeWeeklyData());
  });

  // ── Output type & validity ──────────────────────────────────────────────

  it('returns a Buffer', () => {
    expect(Buffer.isBuffer(pdfBuffer)).toBe(true);
  });

  it('starts with the PDF magic bytes %PDF', () => {
    expect(pdfBuffer.slice(0, 4).toString()).toBe('%PDF');
  });

  it('produces a non-trivial file (> 5 KB)', () => {
    expect(pdfBuffer.length).toBeGreaterThan(5 * 1024);
  });

  // ── Schedule metadata ───────────────────────────────────────────────────

  it('embeds the week number', () => {
    expect(pdfBuffer.toString('latin1')).toContain('5');
  });

  it('embeds the year', () => {
    expect(pdfBuffer.toString('latin1')).toContain('2025');
  });

  // ── Table content ───────────────────────────────────────────────────────

  it('embeds work item ASCII content strings', () => {
    const raw = pdfBuffer.toString('latin1');
    // PDFKit encodes text as PDF string literals; ASCII content is usually visible
    expect(raw).toContain('Hospital quality review meeting');
    expect(raw).toContain('Budget planning session');
    expect(raw).toContain('Staff training on new EHR system');
  });

  it('embeds location values', () => {
    const raw = pdfBuffer.toString('latin1');
    expect(raw).toContain('Conference Room A');
    expect(raw).toContain('Finance Office');
  });

  it('embeds participant text', () => {
    const raw = pdfBuffer.toString('latin1');
    expect(raw).toContain('Dr. Anh');
    expect(raw).toContain('Director Nam');
  });

  it('embeds formatted date values', () => {
    const raw = pdfBuffer.toString('latin1');
    expect(raw).toContain('03/02/2025');
    expect(raw).toContain('04/02/2025');
    expect(raw).toContain('05/02/2025');
  });

  // ── Edge: empty items list ──────────────────────────────────────────────

  it('produces a valid PDF when items list is empty', async () => {
    const buf = await SchedulePdfService.buildWeeklyWorkPdf(
      makeWeeklyData({ items: [] })
    );
    expect(Buffer.isBuffer(buf)).toBe(true);
    expect(buf.slice(0, 4).toString()).toBe('%PDF');
  });

  // ── Edge: null location / participants rendered as '—' ──────────────────

  it('handles null location and participants without throwing', async () => {
    const data = makeWeeklyData({
      items: [{ work_date: '2025-02-06', content: 'Test item', location: null, participants: null }]
    });
    const buf = await SchedulePdfService.buildWeeklyWorkPdf(data);
    expect(Buffer.isBuffer(buf)).toBe(true);
    expect(buf.slice(0, 4).toString()).toBe('%PDF');
  });

  // ── Edge: single item ───────────────────────────────────────────────────

  it('handles a single work item correctly', async () => {
    const data = makeWeeklyData({
      items: [{ work_date: '2025-02-10', content: 'OnlyEntry123', location: 'Room1', participants: 'Alice' }]
    });
    const buf = await SchedulePdfService.buildWeeklyWorkPdf(data);
    expect(buf.toString('latin1')).toContain('OnlyEntry123');
  });

  // ── Type-guard ──────────────────────────────────────────────────────────

  it('throws when called with a duty schedule object', async () => {
    await expect(
      SchedulePdfService.buildWeeklyWorkPdf({ ...makeWeeklyData(), schedule_type: 'duty' })
    ).rejects.toThrow('buildWeeklyWorkPdf requires a weekly_work schedule data object');
  });

  it('throws when called with null', async () => {
    await expect(SchedulePdfService.buildWeeklyWorkPdf(null))
      .rejects.toThrow('buildWeeklyWorkPdf requires a weekly_work schedule data object');
  });

  // ── Large dataset: many rows ────────────────────────────────────────────

  it('handles 30 work items (page-break stress test)', async () => {
    const items = Array.from({ length: 30 }, (_, i) => ({
      work_date:    `2025-02-${String((i % 28) + 1).padStart(2, '0')}`,
      content:      `WorkItem_${i + 1}: Lorem ipsum dolor sit amet, scheduled activity`,
      location:     `Room ${i + 1}`,
      participants: `Staff member ${i + 1}`,
    }));
    const buf = await SchedulePdfService.buildWeeklyWorkPdf(makeWeeklyData({ items }));
    expect(Buffer.isBuffer(buf)).toBe(true);
    expect(buf.slice(0, 4).toString()).toBe('%PDF');
    expect(buf.length).toBeGreaterThan(10 * 1024);
  });
});
